name: RSCEditor
version: ${project.version}
main: com.balugaq.rsceditor.implementation.RSCEditor
api-version: 1.18
depend: [ Slimefun, RykenSlimefunCustomizer ]
authors: [ balugaq ]
description: An editor for RykenSlimeCustomizer.
commands:
  rsceditor:
    aliases:
      - rsce
